### PR TITLE
add gradientAngle and gradientLength properties

### PR DESCRIPTION
**Pull request by abalazsik**
With this commit now you can set the angle (and the length) of the background gradient

### CODE REVIEW

**Comment by tipsy** [comment]
Thanks @abalazsik - I haven't touched this in many years, but I am going to release a v2 now. Do you want this included? I am wondering if maybe it should be possible to just specify a gradient, not a "start" and "stop" color.

**Comment by abalazsik** [comment]
Hi! I rebased my merge request.
It looks like js canvas does not support it natively, so you have to parse it from a string. I just wanted to set the gradient angle, having a constant direction is too boring for my taste. I'm using this lib in one of my private projects.

**Comment by tipsy** [comment]
> It looks like js canvas does not support it natively, so you have to parse it from a string.

It seems like you're right, that's a bit disappointing. Thanks your rebasing the PR, I'll have a look soon :)

**Comment by tipsy** [comment]
Looks good, thank you!

**Pull request merged**
